---
title: "Quels services ?"
format: 
  html:
    page-layout: full
---


# Thérapie individuelle d’une heure

::: {.justify}

* Séances en cabinet : 
  - A Montpellier, au Centre de thérapie des Arceaux, 18 rue de Louvain 34000 (Les Arceaux)
  -	A Paris, au Centre Sésame, 39 boulevard de Magenta 75010 (Arrêts Bonsergeant, République, Gare de l’Est, Château d’eau)
  
* Séances également en visio et par téléphone

* Tarifs : 
  - 80 euros à Paris et dans les grandes métropoles européennes, 
  - 70 euros à Montpellier et dans le reste de la France,
  - Des formules solidaires sont envisageables en fonction de mes possibilités et de l’engagement des patients

* Les RDV peuvent être pris :
  - par téléphone au 06 64 30 34 24. N’hésitez pas à laisser un message je vous rappelerai
  - sur la plate-forme des [pages jaunes](https://www.pagesjaunes.fr/pros/60371469){target="_blank"}

# Conférences, formations et ateliers

* Conférences/formations/ateliers sur les questions de genre et de sexualité auprès de professionnels de la santé mentale ou de profanes: tarifs à définir avec les associations ou les institutions demandeuses.


:::
