project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  title: "Marie-Pierre Toutain - Psychanalyse,<br>Rêve-Éveillé-Libre, Gestalt-thérapie"
  navbar:
   background: light
   search: true
   left:
      - href: index.qmd
        text: Chèr.e.s visiteur.euse.s
      - 01_therapie.qmd
      - 02_therapeute.qmd
      - 03_services.qmd
 
   right:
      - contact.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


