---
title: "A propos"
---

## Crédits

### Crédits photographiques

::: {.justify}

* © Gilbert Garcin - [http://www.gilbert-garcin.com/](http://www.gilbert-garcin.com/){target="_blank"}

Un immense remerciement à Philippe Garcin, fils de Gilbert Garcin, qui a eu la gentillesse de m'autoriser à utiliser les photographies de son père pour illustrer en partie ce site.

* © [Gabriel Quirant-Pidet](https://www.gqp.fr/){target="_blank"}

Toute ma gratitude à Gabriel Quirant-Pidet qui a si bien su photographier mon cabinet du 18 rue de Louvain.

* © Centre Sésame Paris X

Un grand merci au Centre Sésame qui m'a autorisée à utiliser l'une de ses photographies pour illustrer mon cabinet du 39 boulevard de Magenta, Paris.

::: 

### Droit d’auteur - Copyright © - réutilisation des contenus
© 2024-2025 Marie-Pierre Toutain

### Outil de gestion de contenu
Ce site a été créé en utilisant la technologie [Quarto](https://quarto.org){target="_blank"}.

## Mentions Légales

### Identification du site
Nom du site : Marie-Pierre Toutain - Psychanalyse, Rêve Eveillé Libre, Gestalt-thérapie

URL complète du site : https://marie-pierretoutain.github.io

### Éditrice du site

Marie-Pierre Toutain

Contact mail : marie-pierre.toutain@wanadoo.fr – Contact téléphonique : + 33 (0)6 64 30 34 24

### Créatrice du site

[Isabelle Sanchez](https://mistea.pages.mia.inra.fr/isabellesanchez/){target="_blank"}

## Cookies
Ce site n'utilise aucun cookie.

